export enum BookingStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  ARRIVAL_CONFIRMED = 'ARRIVAL_CONFIRMED',
  PENDING_COMPLETION_VERIFICATION = 'PENDING_COMPLETION_VERIFICATION',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum CancelledBy {
  USER = 'USER',
  PROVIDER = 'PROVIDER',
  SYSTEM = 'SYSTEM',
}
